# ??????
hjy-community:
  # ??
  name: hjy-community
  # ??
  version: 1.0.0

# ??????
server:
  #????HTTP??
  port: 8080
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # tomcat?????????200
    max-threads: 800
    # Tomcat?????????????25
    min-spare-threads: 30

# ????
logging:
  level:
#    com.msb: debug
    org.springframework: warn

# Spring??
spring:
  profiles:
    active: druid
  # 解决 Spring Boot 2.6+ 与 Swagger 2.9.2 兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis ??
  redis:
    # ??
    host: localhost
    # ??????6379
    port: 6379
    # ??
    password:
    # ??????
    timeout: 10s
    jedis:
      pool:
        # ???????????
        min-idle: 3
        # ???????????
        max-idle: 8
        # ????????????
        max-active: 8
        # #???????????????????????
        max-wait: -1ms
# MyBatis??

# PageHelper????
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## mybatis-plus??
mybatis-plus:
  ## plus??????????????????????????????
  type-aliases-package: com.msb.hjycommunity.**.domain
  ## mybatis  mapper.xml???
  mapper-locations: classpath:mapper/**/*Mapper.xml
  ## mybatis  config???????

  config-location: classpath:mybatis/mybatis-config.xml
  ## ????
  global-config:
    db-config:
      ## id???????id
      id-type: assign_id
    ## ???mybatis-plus?banner
    banner: false

# token??
token:
  # ???????
  header: Authorization
  # ????
  secret: msbhjy
  # ????????30???
  expireTime: 30
